FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

RUN ls

# Install all dependencies (including dev)
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Start in development mode with watch
CMD ["npm", "run", "start:debug"]

